name: Go Socket BE

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: go_socket
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306
        options:
          --health-cmd="mysqladmin ping"  
          --health-interval=5s   
          --health-timeout=2s    
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Test with Gradle
        env:
            SPRING_PROFILES_ACTIVE: test
            DB_URL: ${{ secrets.DB_URL }}
            DB_USERNAME: ${{ secrets.DB_USERNAME }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: ./gradlew clean test

      - name: Backend CI Discord Notification (Success)
        if: ${{ success() }}
        uses: sarisia/actions-status-discord@v1
        with:
          title: ✅ Backend CI success ✅
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: 00FF00

      - name: Backend CI Discord Notification (Failure)
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          title: ❗️ Backend CI failed ❗️
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: FF0000