name: Go Socket BE

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Test with Gradle
        run: ./gradlew clean test

      - name: Build with Gradle
        env:
          SPRING_PROFILES_ACTIVE: test
        run: ./gradlew clean build

      - name: Backend CI Discord Notification (Success)
        if: ${{ success() }}
        uses: sarisia/actions-status-discord@v1
        with:
          title: ✅ Backend CI success ✅
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: 00FF00

      - name: Backend CI Discord Notification (Failure)
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          title: ❗️ Backend CI failed ❗️
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: FF0000